apiVersion: v1
kind: Secret
metadata:
  name: https-private-repo-secret
  namespace: argo
  labels:
     argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/nasirnjs/ci-cd-k8s.git
  username: nasirnjs
  password: TOKEN