apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webinar-code-to-cloud
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.custom: nasir.uddin@anwargroup.com
spec:
  project: default
  source:
    repoURL: https://github.com/askyourmentors/webinar-code-to-cloud-conf.git
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
    - Prune=true
    - SelfHeal=true
