apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namspace: argocd
data:
  context: |
    argocdUrl: https://172.17.18.185/applications
  service.email.custom: |
    username: argocduser
    password: HiY514KOkwX
    host: mail.smtp2go.com
    port: 587
    from: notification@kcddhaka.org
  template.app-sync-succeeded: |
    email:
      subject: Application {{.app.metadata.name}} has been successfully synced.
    message: |
      {{if eq .serviceType "slack"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.
      Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .
  trigger.on-sync-succeeded: |
    - when: app.status.operationState.phase == "Succeeded"
      send: 
        - app-sync-succeeded
