apiVersion: v1
kind: Service
metadata:
  namespace: kinder
  name: kinder-fe-service
  annotations:
    argocd.argoproj.io/sync-options: SkipPrune=true
spec:
  selector:
    app: kinder-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer